const categoryTypes = {
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
  FETCH_CATEGORY_HEADLINES_START: "FETCH_CATEGORY_HEADLINES_START",
  FETCH_CATEGORY_HEADLINES_SUCCESS: "FETCH_CATEGORY_HEADLINES_SUCCESS",
  FETCH_CATEGORY_HEADLINES_FAILURE: "FETCH_CATEGORY_HEADLINES_FAILURE",
  FETCH_SINGLE_CATEGORY_HEADLINES_START:
    "FETCH_SINGLE_CATEGORY_HEADLINES_START",
  FETCH_SINGLE_CATEGORY_HEADLINES_SUCCESS:
    "FETCH_SINGLE_CATEGORY_HEADLINES_SUCCESS",
  FETCH_SINGLE_CATEGORY_HEADLINES_FAILURE:
    "FETCH_SINGLE_CATEGORY_HEADLINES_FAILURE"
};

export default categoryTypes;
