const headlineTypes = {
  FETCH_TOP_HEADLINES_START: "FETCH_TOP_HEADLINES_START",
  FETCH_TOP_HEADLINES_SUCCESS: "FETCH_TOP_HEADLINES_SUCCESS",
  FETCH_TOP_HEADLINES_FAILURE: "FETCH_TOP_HEADLINES_FAILURE"
};

export default headlineTypes;
