const headlineTypes = {
  FETCH_TOP_HEADLINES_START: "FETCH_TOP_HEADLINES_START",
  FETCH_TOP_HEADLINES_SUCCESS: "FETCH_TOP_HEADLINES_SUCCESS",
  FETCH_SHUFFLED_HEADLINES_SUCCESS: "FETCH_SHUFFLED_HEADLINES_SUCCESS",
  FETCH_TOP_HEADLINES_FAILURE: "FETCH_TOP_HEADLINES_FAILURE",
  FETCH_SINGLE_HEADLINE_START: "FETCH_SINGLE_HEADLINE_START",
  FETCH_SINGLE_HEADLINE_SUCCESS: "FETCH_SINGLE_HEADLINE_SUCCESS",
  FETCH_SINGLE_HEADLINE_FAILURE: "FETCH_SINGLE_HEADLINE_FAILURE"
};

export default headlineTypes;
