const CountriesList = [
  { name: "Argentina", shortName: "AR", emoji: "🇦🇷" },
  { name: "Australia", shortName: "AU", emoji: "🇦🇺" },
  { name: "Austria", shortName: "AT", emoji: "🇦🇹" },
  { name: "Belgium", shortName: "BE", emoji: "🇧🇪" },
  { name: "Brazil", shortName: "BR", emoji: "🇧🇷" },
  { name: "Bulgaria", shortName: "BG", emoji: "🇧🇬" },
  { name: "Canada", shortName: "CA", emoji: "🇨🇦" },
  { name: "China", shortName: "CN", emoji: "🇨🇳" },
  { name: "Colombia", shortName: "CO", emoji: "🇨🇴" },
  { name: "Cuba", shortName: "CU", emoji: "🇨🇺" },
  { name: "Czech Republic", shortName: "CZ", emoji: "🇨🇿" },
  { name: "Egypt", shortName: "EG", emoji: "🇪🇬" },
  { name: "France", shortName: "FR", emoji: "🇫🇷" },
  { name: "Germany", shortName: "DE", emoji: "🇩🇪" },
  { name: "Greece", shortName: "GR", emoji: "🇬🇷" },
  { name: "Hong Kong", shortName: "HK", emoji: "🇭🇰" },
  { name: "Hungary", shortName: "HU", emoji: "🇭🇺" },
  { name: "India", shortName: "IN", emoji: "🇮🇳" },
  { name: "Indonesia", shortName: "ID", emoji: "🇮🇩" },
  { name: "Ireland", shortName: "IE", emoji: "🇮🇪" },
  { name: "Israel", shortName: "IL", emoji: "🇮🇱" },
  { name: "Italy", shortName: "IT", emoji: "🇮🇹" },
  { name: "Japan", shortName: "JP", emoji: "🇯🇵" },
  { name: "Latvia", shortName: "LV", emoji: "🇱🇻" },
  { name: "Lithuania", shortName: "LT", emoji: "🇱🇹" },
  { name: "Malaysia", shortName: "MY", emoji: "🇲🇾" },
  { name: "Mexico", shortName: "MX", emoji: "🇲🇽" },
  { name: "Morocco", shortName: "MA", emoji: "🇲🇦" },
  { name: "Netherlands", shortName: "NL", emoji: "🇳🇱" },
  { name: "New Zealand", shortName: "NZ", emoji: "🇳🇿" },
  { name: "Nigeria", shortName: "NG", emoji: "🇳🇬" },
  { name: "Norway", shortName: "NO", emoji: "🇳🇴" },
  { name: "Philippines", shortName: "PH", emoji: "🇵🇭" },
  { name: "Poland", shortName: "PL", emoji: "🇵🇱" },
  { name: "Portugal", shortName: "PT", emoji: "🇵🇹" },
  { name: "Romania", shortName: "RO", emoji: "🇷🇴" },
  { name: "Russia", shortName: "RU", emoji: "🇷🇺" },
  { name: "Saudi Arabia", shortName: "SA", emoji: "🇸🇦" },
  { name: "Serbia", shortName: "RS", emoji: "🇷🇸" },
  { name: "Singapore", shortName: "SG", emoji: "🇸🇬" },
  { name: "Slovakia", shortName: "SK", emoji: "🇸🇰" },
  { name: "Slovenia", shortName: "SI", emoji: "🇸🇮" },
  { name: "South Africa", shortName: "ZA", emoji: "🇿🇦" },
  { name: "South Korea", shortName: "KR", emoji: "🇰🇷" },
  { name: "Sweden", shortName: "SE", emoji: "🇸🇪" },
  { name: "Switzerland", shortName: "CH", emoji: "🇨🇭" },
  { name: "Taiwan", shortName: "TW", emoji: "🇹🇼" },
  { name: "Thailand", shortName: "TH", emoji: "🇹🇭" },
  { name: "Turkey", shortName: "TR", emoji: "🇹🇷" },
  { name: "United Arab Emirates", shortName: "AE", emoji: "🇦🇪" },
  { name: "Ukraine", shortName: "UA", emoji: "🇺🇦" },
  { name: "United Kingdom", shortName: "GB", emoji: "🇬🇧" },
  { name: "United States", shortName: "US", emoji: "🇺🇸" },
  { name: "Venezuela", shortName: "VE", emoji: "🇻🇪" }
];

export default CountriesList;
